# Generated by Django 2.0.6 on 2018-07-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_all_borrowed_books', 'can_edit_all_borrowed_books'),)},
        ),
    ]
